config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get '/home', to: 'pages#home' #dashboard page
  get '/faq', to: 'pages#faq' #dasahboard page

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "deliverables/:id/data", to: "deliverables#data", as: 'deliverables_data'
  # patch "/deliverables/:id", to: "deliverables#update" , as: 'update_deliverable'

  get '/test', to: 'pages#test'

  get '/dashboard', to: 'pages#dashboard'
  # get '/projects/:id/edit', to:'pages#dashboard'
  get '/error', to: 'pages#error'

  get '/notifications', to: 'notifications#index'

  resources :notifications, only: %i[update destroy]

  resources :projects, except: [:show] do
    resources :deliverables, only: %i[new create]
    post 'project_confirmations/create'
    get 'confirm', to: 'projects#confirm'
    get 'sent', to: 'projects#sent'
  end

  get 'projects/:id(/:token)(/:role_token)', to: 'projects#show', as: 'show_project'
  get 'projects/:id/:token/:role_token/sign_up', to: 'projects#sign_up'

  resources :deliverables, only: %i[show destroy edit update index] do
    resources :drafts, only: %i[new create index]
  end

  resources :drafts, only: [:show] do
    resources :comments, only: %i[index new create]
    get 'approve', to: 'drafts#approve'
    get 'reject', to: 'drafts#reject'
  end

  resources :comments, only: [:show] do
    resources :replies, only: %i[new create]
  end

  resources :organisations

  resources :roles, only: [:update]

  namespace :api do
    namespace :v1 do
      resources :deliverables, only: [:index]
      resources :projects, only: %i[index show] do
        get 'deliverables', to: 'projects#deliverables'
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :draft

  has_many :replies, class_name: "Comment", foreign_key: "parent_id", dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @draft = Draft.find(params[:draft_id])
    @comment = Comment.new
  end

  def create
    @draft = Draft.find(params[:draft_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    @draft.comments << @comment
    @draft.save!

    @comment.save!

    if comment_params[:parent_id].nil?
      CommentNotification.with(comment: @comment, user: current_user, draft: @draft).deliver(@draft.user)
    else
      @parent = Comment.find(comment_params[:parent_id])
      CommentNotification.with(comment: @comment, user: current_user).deliver(@parent.user)
    end


    respond_to do |format|
      format.html { redirect_to draft_path(@draft) }
      format.json # Follow the classic Rails flow and look for a create.json view
      format.text {render partial: 'comments/comment', locals: { comment: @comment }, formats: [:html] }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end
end

app/views/comments/_comment.html.erb
<% if comment.parent_id.nil? %>
  <div class="comment-card card-white" data-controller="insert-comments">
    <div>
      <div class="author-details">
        <div>
          <img src="<%=comment.user.profile_pic%>" alt="avatar" class="avatar">
        </div>
        <div>
          <p class="mb-2"><%= comment.user.first_name %></p>
          <p>
            <% if (Time.now - comment.created_at)< 1.hour%>
              <%= distance_of_time_in_words_to_now(comment.created_at)%> ago
            <% else %>
              <%= comment.created_at.strftime("%I:%M%p %b %e") %>
            <% end %>
          </p>
        </div>
      </div>
      <div class="comment-content">
        <p><%= comment.content %></p>
      </div>
    </div>
    <%# if the comment has any replies, you iterate it %>
    <div data-insert-comments-target="replies" <%if (comment.replies.length >= 3 ) %> class="d-none" <%end%>>
      <%= render partial: "comments/reply", collection: comment.replies, as: :comment %>
    </div>
    <% if comment.replies.length >= 3 %>
      <a class="see-more" data-insert-comments-target="viewMore" data-action="click->insert-comments#viewReplies">see <%=comment.replies.length%> comments</a>
    <% end %>
    <div class='text-right'>
      <a class="comment-btn" data-insert-comments-target="newReply"  data-action="click->insert-comments#newReply">reply</a>
    </div>

    <%# create a form, but hidden %>
    <% if comment.parent_id.nil? %>
      <%= simple_form_for Comment.new, method: :post, url: draft_comments_path(@draft), data: {insert_comments_target: "form", action: "insert-comments#createReply"}, html: {class: "d-none mt-1"} do |f| %>
        <%= f.input :content, placeholder: "comment here", label: false,
          input_html: {
            data: {
              insert_comments_target: "content"
              }}%>
        <%= f.hidden_field :parent_id, value: comment.id %>
        <div class="text-right">
          <%= f.submit "reply", data: {insert_comments_target: "submit"}, class: "comment-btn" %>
        </div>
      <% end %>
    <% end %>

  </div>
<% else %>
  <%= render partial: "comments/reply", locals: {comment: comment} %>
<% end %>

app/views/comments/_new.html.erb
<%= simple_form_for [@draft, @comment], data: {insert_comments_target: "form"}, html: {class: "comment-form"} do |f| %>
  <%= f.input :content, name: "content", placeholder: "your comment here", label: false,
    input_html: {
      data: {
        insert_comments_target: "content"
        }}%>
  <div class="text-right">
    <%= f.submit "Add comment", class: "comment-btn" %>
  </div>
<% end %>

app/views/comments/_reply.html.erb
<hr>
<div class="reply-card">
  <div class="author-details">
    <div>
      <img src="<%=comment.user.profile_pic%>" alt="avatar" class="avatar">
    </div>
    <div>
      <p><%= comment.user.first_name %></p>
      <p>
        <% if (Time.now - comment.created_at)< 1.hour%>
          <%= distance_of_time_in_words_to_now(comment.created_at)%> ago
        <% else %>
          <%= comment.created_at.strftime("%I:%M%p %b %e") %>
        <% end %>
      </p>
    </div>
  </div>
  <div>
    <p><%= comment.content %></p>
  </div>
</div>