config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get '/home', to: 'pages#home' #dashboard page
  get '/faq', to: 'pages#faq' #dasahboard page

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "deliverables/:id/data", to: "deliverables#data", as: 'deliverables_data'
  # patch "/deliverables/:id", to: "deliverables#update" , as: 'update_deliverable'

  get '/test', to: 'pages#test'

  get '/dashboard', to: 'pages#dashboard'
  # get '/projects/:id/edit', to:'pages#dashboard'
  get '/error', to: 'pages#error'

  get '/notifications', to: 'notifications#index'

  resources :notifications, only: %i[update destroy]

  resources :projects, except: [:show] do
    resources :deliverables, only: %i[new create]
    post 'project_confirmations/create'
    get 'confirm', to: 'projects#confirm'
    get 'sent', to: 'projects#sent'
  end

  get 'projects/:id(/:token)(/:role_token)', to: 'projects#show', as: 'show_project'
  get 'projects/:id/:token/:role_token/sign_up', to: 'projects#sign_up'

  resources :deliverables, only: %i[show destroy edit update index] do
    resources :drafts, only: %i[new create index]
  end

  resources :drafts, only: [:show] do
    resources :comments, only: %i[index new create]
    get 'approve', to: 'drafts#approve'
    get 'reject', to: 'drafts#reject'
  end

  resources :comments, only: [:show] do
    resources :replies, only: %i[new create]
  end

  resources :organisations

  resources :roles, only: [:update]

  namespace :api do
    namespace :v1 do
      resources :deliverables, only: [:index]
      resources :projects, only: %i[index show] do
        get 'deliverables', to: 'projects#deliverables'
      end
    end
  end
end

app/models/draft.rb
class Draft < ApplicationRecord
  mount_uploaders :attachments, AttachmentUploader # Tells rails to use this uploader for this model.
  belongs_to :deliverable
  has_many :comments, dependent: :destroy
  belongs_to :user

end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  before_action :set_draft, only: [:show]

  def new
    @deliverable = Deliverable.find(params[:deliverable_id])
    @draft = Draft.new
  end

  def show
    @deliverable = @draft.deliverable
    @client = Organisation.find(@deliverable.project.client_id)
    @status_color = case @draft.status
                    when "pending"
                      "btn-sync-info"
                    when "approved"
                      "btn-sync-success"
                    when "rejected"
                      "btn-sync-danger"
                    end
    @comments = @draft.comments.select { |comment| comment.parent_id.nil?}
    @comment = Comment.new
    @project = @draft.deliverable.project
    @approver = ProjectUser.find_by(project_id: @project).role.name
  end

  def create
    @deliverable = Deliverable.find(params[:deliverable_id])
    @draft = Draft.new(draft_params)
    @draft.deliverable = @deliverable
    @draft.user = current_user
    @draft.status = "pending"
    if @draft.save!
      redirect_to draft_path(@draft), notice: "Your draft has been uploaded."
    else
      render "new"
    end
  end

  def approve
    @draft = Draft.find(params[:draft_id])
    @draft.status = "approved"
    @draft.save!
    DraftStatus.with(draft: @draft, user: current_user, action: "approved").deliver(@draft.user)
    redirect_to draft_path(@draft)
  end

  def reject
    @draft = Draft.find(params[:draft_id])
    @draft.status = "rejected"
    @draft.save!
    DraftStatus.with(draft: @draft, user: current_user, action: "rejected").deliver(@draft.user)
    redirect_to draft_path(@draft)
  end

  private
  def draft_params
    params.require(:draft).permit(:description, {attachments: []})
  end

  def set_draft
    @draft = Draft.find(params[:id])
    @project = @draft.deliverable.project
    redirect_to error_path if @project.user != current_user && !(@project.users.include?(current_user))
  end

  def record_not_found
    render "pages/error", status: 404
  end

end

app/views/drafts/_draft.html.erb
<a href="<%=draft_path(draft)%>" class="text-decoration-none">
  <div class="deliv-drafts d-flex align-items-center card-flat my-1">
    <div class="submitted-date">
      submitted <br>
      <%= draft.created_at.strftime("%b %e, %a") %>
    </div>
    <div class="summary">
      <div class="description pr-1">
        <p class="text-left"><%= draft.description.length > 85 ? draft.description[0..85] + "..." : draft.description %></p>
      </div>
      <div class="status">
        <%
        btn_color = case draft.status
          when "pending"
          "btn-sync-info"
          when "approved"
          "btn-sync-success"
          when "rejected"
          "btn-sync-danger"
          end
            %>
        <p class="btn <%=btn_color%> view-draft-btn"><%= draft.status %></p>
      </div>
    </div>
  </div>
</a>

app/views/drafts/show.html.erb
<div class="container mb-5">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb breadcrumb-custom">
      <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
      <li class="breadcrumb-item"><a href="/projects/<%= @draft.deliverable.project.id %>"><%= @draft.deliverable.project.name %></a></li>
      <li class="breadcrumb-item"><a href="/deliverables/<%= @draft.deliverable.id%>"><%= @draft.deliverable.deliverable_type%></a></li>
      <li class="breadcrumb-item active" aria-current="page">Draft</li>
    </ol>
  </nav>

<%# heading %>
  <div class="card-white py-3 pl-3 mb-4 d-flex align-items-center justify-content-between">
    <div>
      <div class="review-card-title header-lg"><%=@client.name %>: <%= @draft.deliverable.project.name %></div>
      <div class="review-card-description header-md"><%= @draft.deliverable.project.description %></div>
    </div>
    <%# brand view -- approve and reject buttons %>
    <% if (@draft.deliverable.project.brand == current_user.organisation) && (@draft.status == "in progress") && (@approver == 'admin') %>
      <a class="comment-btn mx-1 w-15" href="<%=draft_approve_path(@draft)%>">Approve draft</a>
      <a class="comment-btn mx-1 w-15" href="<%=draft_reject_path(@draft)%>">Reject draft</a>
    <% end %>
  </div>

<%# submitted draft %>
  <div class="card-frosted draft-panel" data-controller="toggle">
    <div class="d-flex justify-content-between align-items-center">
      <div class="custom-header py-3 pl-3">
      <div class="d-flex align-items-center">
        <div>
          <h2 class="mb-0 mr-1 header-lg"><%= @draft.deliverable.deliverable_type %></h2>
        </div>
        <div>
          <span class="draft-status <%=@status_color%>"><%=@draft.status%></span>
        </div>
      </div>
        <p class='pl-1 pb-3 text-muted'>Deliverable due in  <%= pluralize (@draft.deliverable.due_date - Date.today).to_i,"day"%></p>
        <h3><%= @draft.deliverable.description %></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-8 sticky-panel">
        <div class="pl-3 ">
          <div class='d-flex flex-column justify-content-start pb-5 p-2 preview card-frosted'>
            <ul class="list-group">
              <% @draft.attachments.each do |attachment| %>
                <li class="d-block w-100">
                  <% if attachment.url.match(/\S*.pdf$/) %>
                    <embed src="<%= attachment.url %>" type="application/pdf" class="w-100 pdf-draft"/>
                  <% else %>
                    <img src="<%= attachment.url %>" class="w-100 mb-2" alt="image">
                  <% end %>
                </li>
              <% end %>
            </ul>
            <div class='pt-4'>
              <h3>Description:</h3>
              <p><%= @draft.description %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-4">
        <div class="comments-list">
          <div class="new-comment">
            <div class="comment-btn block-btn" data-toggle-target="button" data-action="click->toggle#newComment">
              <i class="fas fa-comments mx-2"></i>Add new comment
            </div>
            <div data-toggle-target="commentForm" class="d-none">
              <%= render 'comments/new'%>
            </div>
          </div>
          <%= render @comments %>
        </div>
      </div>
    </div>
  </div>
</div>

                <%# if attachment.content_type == "application/pdf" %>
                  <%#= link_to "Download PDF", @draft.attachment.url, target: :blank %>
                <%# else %>

app/views/drafts/trash.html.erb
<div class="card-frosted panel">
  <div class="custom-header">
    <h1><%= @draft.deliverable.deliverable_type %></h1>
    <h3><%= @draft.deliverable.description %></h3>
  </div>
  <div>
    <% if @draft.attachment.content_type == "application/pdf" %>
      <%= link_to "Download PDF", @draft.attachment.url, target: :blank %>
    <% else %>
      <img src="<%= @draft.attachment.url %>" alt="image" width='300' height='300'>
    <% end %>
  </div>

<div class="container">
  <div class="d-flex justify-content-center">
    <div>
      <h2>Comments</h2>
        <ul>
          <%= render @comments %>
        </ul>
    </div>
    <div>
      <%= render 'comments/new' %>
    </div>
  </div>
</div>
</div>